---
- hosts: all
  become: true
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: install IUS repository
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: latest
    - name: install dev tools
      yum:
        # git default version is 1.8.x on centos7. Installing it version 2.x that is retrieve from IUS repo.
        name: 'git216'
        state: latest
    - name: install docker drive utils
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
    - name: add docker repository
      yum_repository:
        name: docker
        description: docker-ce yum repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
    - name: install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
    - name: start docker
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: pull default docker image
      docker_container:
        name: centos7
        source: pull
    - name: create default docker conrainer
      docker_container:
        name: centos
        image: centos:centos7
        volumes:
          - name: /vagrant:/wine